# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cff310b4944a179db60f793594687791722568fb861a95c5473052105779efa9b8669d15327fb84f7340a29b82fad413e82997314af8eb009fed5134b1767ac

test:
  secret_key_base: e5e385ddd780d6ebc24c3830b174c0fe96bbf64d6f9ef803ca89a8fbdc553e0d20f360a1e09ca3af125debcceb48b760bcbb11420fbc85ea0287843374ead770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
